# Site settings
title: Dollars & Sense of Westworld
description: "We try to figure out if it would be possible to run Westworld as an actual business."
url: "http://www.dollarsandsenseofwestworld.com"
author:
- name: "Dollars and Sense of Westworld"
  url: "https://twitter.com/_dasow"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
